site_name: ds-event-stream-python-sdk
site_description: Python SDK for Kafka event streaming (Grasp Labs)
site_author: Grasp Labs
repo_url: https://github.com/grasp-labs/ds-event-stream-python-sdk
nav:
  - Home: README.md
  - Usage: usage.md
  - API Reference: api.md
  - Testing: testing.md
  - License: license.md
theme:
  name: material
