site_name: ds-event-stream-python-sdk
site_description: Python SDK for Kafka event streaming (Grasp Labs)
site_author: Grasp Labs
repo_url: https://github.com/grasp-labs/ds-event-stream-python-sdk
nav:
  - Home: docs/README.md
  - Usage: docs/usage.md
  - API Reference: docs/api.md
  - Testing: docs/testing.md
  - License: docs/license.md
theme:
  name: material
