name: Simple PyPI Deploy

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Get current version
        id: current_version
        run: |
          CURRENT_VERSION=$(grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Build package
        run: |
          python -m build
          echo "Package built successfully"
          ls -la dist/

      - name: Check package
        run: |
          twine check dist/*
          echo "Package validation passed"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_KEY }}
          verbose: true

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.current_version.outputs.current_version }}
          release_name: Release v${{ steps.current_version.outputs.current_version }}
          body: |
            ## 🚀 Release v${{ steps.current_version.outputs.current_version }}

            **Manual deployment to PyPI**

            ### Links
            - **PyPI Package:** https://pypi.org/project/ds-event-stream-python-sdk/${{ steps.current_version.outputs.current_version }}/
            - **Documentation:** https://grasp-labs.github.io/ds-event-stream-py-sdk/

            ### Installation
            ```bash
            pip install ds-event-stream-python-sdk==${{ steps.current_version.outputs.current_version }}
            ```
          draft: false
          prerelease: false
